/**
 * @see https://tc39.es/proposal-unified-intl-numberformat/section6/locales-currencies-tz_proposed_out.html#sec-issanctionedsimpleunitidentifier%7Cunit
 */

export  enum Unit {
    Acre = 'acre',
    Bit = 'bit',
    Byte = 'byte',
    Celsius = 'celsius',
    Centimeter = 'centimeter',
    Day = 'day',
    Degree = 'degree',
    Fahrenheit = 'fahrenheit',
    FluidOunce = 'fluid-ounce',
    Foot = 'foot',
    Gallon = 'gallon',
    Gigabit = 'gigabit',
    Gigabyte = 'gigabyte',
    Gram = 'gram',
    Hectare = 'hectare',
    Hour = 'hour',
    Inch = 'inch',
    Kilobit = 'kilobit',
    Kilobyte = 'kilobyte',
    Kilogram = 'kilogram',
    Kilometer = 'kilometer',
    Liter = 'liter',
    Megabit = 'megabit',
    Megabyte = 'megabyte',
    Meter = 'meter',
    Mile = 'mile',
    MileScandinavian = 'mile-scandinavian',
    Milliliter = 'milliliter',
    Millimeter = 'millimeter',
    Millisecond = 'millisecond',
    Minute = 'minute',
    Month = 'month',
    Ounce = 'ounce',
    Percent = 'percent',
    Petabyte = 'petabyte',
    Pound = 'pound',
    Second = 'second',
    Stone = 'stone',
    Terabit = 'terabit',
    Terabyte = 'terabyte',
    Week = 'week',
    Yard = 'yard',
    Year = 'year',
}
